server:
  port: 8080
spring:
  main:
    allow-bean-definition-overriding: true #允许覆盖bean定义，默认false
  application:
    #应用名称
    name: hzf_take_out
  cache:
    redis:
      time-to-live: 1800000
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: 123456
  shardingsphere:
    datasource:
      names: master,slave
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.10.128:3306/reggie?characterEncoding=utf-8  #linux1的地址
        username: root
        password: 123456
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.10.129:3306/reggie?characterEncoding=utf-8  #linux2的地址
        username: root
        password: 123456
    masterslave:      # 读写分离配置
      load-balance-algorithm-type: round_robin #轮询 如果有多个从库会轮询着读
      name: dataSource      # 最终的数据源名称
      master-data-source-name: master      # 主库数据源名称
      slave-data-source-names: slave      # 从库数据源名称列表，多个逗号分隔
    props:
        sql:
          show: true #开启SQL显示，默认false
#    sharding:
#      default-data-source-name: master
mybatis-plus:
  configuration:
    #address_book->AddressBook
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\zuomian\DA4\JAVA\reggie\upload\
  path2: ./src/main/resources/upload/  #最后加斜杠没用，调用的时候就没了,测试文件在Temptest,CommonController拼接字符串的时候还是得手动再加一个
  path3: .\ #加不加斜杠都没用，
  path4: ..  #.代表项目最顶层根目录,比如本项目就是reggie目录,  ..代表上级目录

redis:
  host: localhost
  port: 6379
#  password: 未设置
  database: 0
